### ISSUE TITLE
☂️ Docs update for Q3 2024 release

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#10838]
Issues created for the Q3 2024 release:

- [ ] Document multi-view [10773](https://github.com/flutter/website/issues/10773)
- [x] Update the widget catalog with missing Cupertino widgets [8739](https://github.com/flutter/website/pull/8739)
- [x] Note that CanvasKit is now the default web renderer [10811](https://github.com/flutter/website/issues/10811)
- [x] Update supported platforms page for Q3 [10812](https://github.com/flutter/website/issues/10812)
- [x] Explain how to create macOS platform views. [9424](https://github.com/flutter/website/issues/9424)
- [x] Add info on migrating iOS plugins to SPM (for now - add app migration info in Q4, eventually CocoaPods support will be dropped) to support both CocoaPods and Swift Package Manager [10806](https://github.com/flutter/website/issues/10806)
- [x] Update the M3 demo on the Material page [10813](https://github.com/flutter/website/issues/10813)
- [x] Add some sort of doc for Predictive Back API on Android (Justin) [10821](https://github.com/flutter/website/issues/10821)
- [ ] Update the adaptive/responsive docs (carryover from Q2). (For one thing, fix the idioms page and publish. Also there’s a bug filed AND Tyler has sent me a list of fixes.) [10769](https://github.com/flutter/website/issues/10769), [9113](https://github.com/flutter/website/issues/9113), [8427](https://github.com/flutter/website/issues/8427).

Removed from the Q3 release:
- Support new ad type: interactive-media. Add a link to the sidenav for the new package. [10808](https://github.com/flutter/website/issues/10808)
- Write an AI cookbook recipe (carryover from Q2) and add it to the App solutions sidenav. [10810](https://github.com/flutter/website/issues/10810)
- Update Deep Link Validator page when iOS app supports deep linking validation. [10814](https://github.com/flutter/website/issues/10814)
- Update Deep Link Validator page when iOS web supports deep linking validation. [10815](https://github.com/flutter/website/issues/10815)
- Update the Impeller page as Impeller is now default and not behind a flag [10805](https://github.com/flutter/website/issues/10805)

**Comment by sfshaza2** [comment]
Q3 release is done.
