### ISSUE TITLE
2018Q3 work log

### ISSUE THREAD

**Issue by chalin** [flutter/website#1195]
Work log. Reorder items using drag-and-drop:

**Active**:

- [ ] [dash] Generate sidenav from YAML data file #1338
- [ ] [dash] Support autogenerated toc using `jekyll-toc` #1259
- [ ] [dash] Cleanup markdown #1342
- [ ] [dash] Sept 26 walkthrough followup #1323

**Next**:
- [ ] Generate a sitemap #1170
- [ ] [dash] adjust code block styling #1334
- [ ] [dash] TOC issues #1272 
- [ ] [dash] Navbar and sidebar styling followup #1269 
- [ ] @chalin: offer feedback (based on site-www experiences) on: [dash] Fix sidebar and toc scrolling issues #1287
- [ ] [dash] Place all/most images under asset management #1213

**Block/awaiting**:
- [ ] Create Docker container with Dart SDK and Flutter SDK #1196

**Later?**
- [ ] ...

**Submitted**:

- [ ] ...

**Done, deployed and confirmed** (selected, see [here for the complete list][closed PRs]):

- [x] [dash] Placement of page TOC? #1337
- [x] Get Started button, support show/hide per page #1325
- [x] Use [linkcheck](https://github.com/filiph/linkcheck) instead of `html-proofer`.
- [x] [dash] Drop `jekyll-redirect-from` gem in favor of Firebase redirect rules #1266
- [x] Drop unused code from `src/_includes/code` #1238
- [x] Reinstate link checking using linkcheck #1239
- [x] Migrate to bootstrap 4 #1194
- [x] Use jekyll-assets for asset management #1193
- [x] Site file reorg: move site sources to src folder #1169
- [x] chore: Jekyll config and site head cleanup #1168
- [ ] ...

**Meta/planning**: N/A

[closed PRs]: https://github.com/flutter/website/milestone/2?closed=1

**Comment by chalin** [comment]
Next quarter: #1355
