### ISSUE TITLE
[dash] Sept 26 walkthrough followup

### ISSUE THREAD

**Issue by chalin** [flutter/website#1323]
- [x] [FG] Vertically center GitHub buttons in h1 line
- [x] [FG] Use standard (400) font weight for body font - #1329
- [x] [FG] Docs landing page: Card padding looks like too much - #1329
- [x] [FG] Sidebar width remains constant regardless of TOC being present or not - #1329

---

- Clicking a TOC entry doesn't position the page at the identified header (the main nav is hiding). FG & PC have discussed alternative solutions. See #1488
- [x] `get-started/install`: use cards for OS-specific install pages
- [x] [PC] Add support for page navigation via previous-page, next-page links. #1322
- [x] [PC] Get Started button, support show/hide per page #1325

**Comment by chalin** [comment]
The last issue will be tracked via #1488. Closing this issue group since everything else is done.
