### ISSUE TITLE
2018Q4 work log

### ISSUE THREAD

**Issue by chalin** [flutter/website#1355]
Work log. Reorder items using drag-and-drop:

**Active**:
- [ ] ...

**Next**:
- [ ] [dash] Identify featured case in showcases.yml file #1443
- [ ] [dash] External links should be visually distinctive #1428
- [ ] [dash] Use sentence case for headings and titles #1368
- [ ] [dash] Automate resync of next/prev link titles and prev link paths #1354
- [ ] [dash] Add next/prev links to cookbook pages #1370
- [ ] [dash] Add breadcrumbs to cookbook pages #1371
- [ ] [dash] Cleanup markdown #1342
- [ ] [dash] Place all/most images under asset management #1213
- [ ] ...

**Block/awaiting**:
- [ ] [dash] Styling followup for active main-nav entries #1435
- [ ] Create Docker container with Dart SDK and Flutter SDK #1196
- [ ] ...

**Later?**
- [ ] ...

**Submitted**:

- [ ] ...

**Done, deployed and confirmed** (selected, see [here for the complete list][closed PRs]):

- [x] [dash] Support autogenerated toc using `jekyll-toc` #1259
- [x] [dash] Don't add "Contents" when there is no TOC even w/o "toc: false" #1609
- [x] [dash] Enable external link checking #1412
- [x] [dash] Merge dash into master - checklist #1365
- [x] [dash] TOC issues #1272 
- [x] [dash] Fix broken external links #1413
- [x] [dash] What to do with pages appearing in two places? #1496
- [x] [dash] Docs active-highlighter missing when viewing docs pages other than `/docs` #1457
- [x] [dash] Fix heading top-nav clearance for dual-id cases #1504
- [x] [dash] Rename "APIs & references" to just "References" #1511
- [x] [dash] Rename path `src/api-and-reference` to `src/references` #1510
- [x] [dash] Sidenav: shorten "Coming from another platform" to "From another platform?" #1514
- [x] Generate a sitemap #1170
- [x] [dash] Accessibility page path doesn't match IA #1497
- [x] [dash][IA] "Using hot reload" is under "Tools" but it isn't a tool #1448
- [x] [dash] Sept 26 walkthrough followup #1323
- [x] [dash] TOC entry doesn't position the page at the identified header #1488
- [x] @chalin: offer feedback (based on site-www experiences) on:
  [dash] Fix sidebar and toc scrolling issues #1287
- [x] [dash] Navbar and sidebar styling followup #1269 
- [x] [dash] Sidenav design: should "Development" and "APIs & References" be open by default? #1452
- [x] [dash][IA] Widget catalogue appears in two places #1425
- [x] [dash][IA] Sidenav supports 3 levels, but IA has 4 levels #1451
- [x] [dash] 2-level side menu entries should be visually distinctive #1450
- [x] [dash] Adjust code block styling #1334
- [x] [dash] Missing syntax highlighter #1419
- [x] [dash] Keep GitHub and Twitter button in mobile main nav #1416
- [x] [dash] Make "Get started" button the first non-brand entry in main nav #1433
- [x] [dash] Add hover and selected design for the top nav item #1420
- [x] [dash] invalid_use_of_protected_member in sample code #1423
- [x] [dash] Generate sidenav from YAML data file #1338
- [x] [dash] Use query parameter to encode selected editor #1410
- [x] [dash] Travis cron jobs are failing #1396
- [x] [dash] Get started: simplify titles and add breadcrumbs #1369
- [x] [dash] Add support for page banners, and add banner to non-landing pages #1352
- [x] [dash] Add banner to landing page #1366
- [x] Add support for page banners, on both landing and other pages #1351
- ~[dash] Semi-autogenerate placeholder pages to avoid 404s for intermediate paths #1444~
- [ ] ...

**Meta/planning**: N/A

[closed PRs]: https://github.com/flutter/website/milestone/3?closed=1
