### ISSUE TITLE
[dash] Merge dash into master - checklist

### ISSUE THREAD

**Issue by chalin** [flutter/website#1365]
- [ ] In `_config.yml` change `branch: dash` to `branch: master`
- [ ] (Optional) In `.travis.yml` drop the dash `deploy` entry
- [ ] Merge dash back into master
- [ ] Fix links to flutter.io design-principles https://github.com/flutter/flutter/pull/22411
