### ISSUE TITLE
Missing from community page

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#1680]
The new community page is beautiful, but it's missing a couple things:

- [ ] a link to the information about China:  /community/china - #2288
- [x] a link to the Spanish site:  https://flutter-es.io - #2287
- [x] a link to the flutter-announce mailing list (#1633) - #2284
