### ISSUE TITLE
Ensure site is mobile-friendly

### ISSUE THREAD

**Issue by chalin** [flutter/website#1951]
For site pages ensure that:

- [ ] **Images** are responsive
  - [x] Recently closed: #1577, #1789
- [ ] **Tables** are responsive, or at least do not cause horizontal page scrolling
- [ ] "Words" aren't overly long, w/o the possibility of a **word-break**. See [Mobile friendly pages: tips & tricks][].

Other specific issues:

- [ ] Homepage issue on mobile #3276
- [ ] Accessibility on Mobile (iOS vs.12) #1574
- [ ] Add Top button #1950 
- [ ] Address site performance #1787

Other ideas open to discussion:

- Consider making the TOC accessible on mobile (as a floating FAB?) rather than only at the top of the page, although solving #1950, might at least alleviate this.

[Mobile friendly pages: tips & tricks]: https://github.com/dart-lang/site-shared/wiki/Mobile-friendly-pages:-tips-&-tricks

**Comment by chalin** [comment]
Unassigning myself since I won't be actively working on this. We'll address issues as the arise.

**Comment by sfshaza2** [comment]
I just spent some time navigating the website on my Pixel 6. It looks great! I'm closing this. If there are any remaining issues, please file a new bug.
