### ISSUE TITLE
2019Q4 work log

### ISSUE THREAD

**Issue by chalin** [flutter/website#3094]
_Reorder items using drag-and-drop_.

**Active**ly being worked on:
- [ ] ...

**Next: top**:

Infrastructure:
- [ ] CI: Use Dart from Flutter bundle rather than separate SDK #3087
- [ ] Refactor and cleanup build scripts: drop Cirrus-only scripts, etc #3186

Testing:
- [ ] CI: ensure that example code is analyzed and tested #3076
- [ ] Code excerpts: use new tooling and infra #2233

**Next**:
- [ ] Upgrade to latest Bootstrap 4.x.y to eliminate warning, use BS toast, etc #2115
- [ ] Ruby Sass gem has reached EOL and should no longer be used #1175
- [ ] CI: run tests using flutter channel versions other than stable #3089
- [ ] Revert or simplify recent change in Animation tutorial code #3073
- [ ] Run `dart tool/next_prev.dart` as part of CI or a precommit check #2217
- [ ] CI: run the formatter on example code #2216
- [ ] Books page issues: isn't mobile friendly, and ToC issues #3218

**Block/awaiting**:
- [ ] CI: use a custom docker container #3184
- [ ] ...

**Submitted**:
- [ ] ...

**Done, deployed and confirmed** (selected, see [here for the complete list][closed PRs]):
- [x] Upgrade ruby and gems #3166 
- [x] Upgrade node to v12 #3167
- [x] Document existing build process.
- [x] CI: cron builds shouldn't trigger site deploys #3127
- [x] CI: build and test over stable flutter channel version #3088
- [x] Don't commit pubspec.lock files for tools and examples #3107
- [x] CI: ensure that code-excerpt freshness is checked #3075
- [ ] ...

[closed PRs]: https://github.com/flutter/website/milestone/9?closed=1

**Comment by parlough** [comment]
I'm going to close this as everything is being tracked in an issue. Thanks!
