### ISSUE TITLE
Cupertino codelab open issues

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#4026]
There are quite a few so I'm collecting them here:
 
- [ ] https://github.com/flutter/website/issues/3911 Problem in Step 5 of Cupertino codelab
- [ ] https://github.com/flutter/website/issues/3477 Building a Cupertino app with Flutter, step 5: Outdated paragraph?
- [ ] https://github.com/flutter/website/issues/3476 Mistake in step 8 of Building a Cupertino app with Flutter: wrong method name
- [ ] https://github.com/flutter/website/issues/3420 Building a Cupertino app with Flutter, Step 10, missing definition of ShoppingCartItem class
- [ ] https://github.com/flutter/website/issues/3229 Building a Cupertino app with Flutter Step 5
- [ ] https://github.com/flutter/website/issues/3221 Update "Add state management" from "Building a Cupertino app with Flutter" to use provider package
- [ ] https://github.com/flutter/website/issues/3063 Guide on 5. Add State Management
- [ ] https://github.com/flutter/website/issues/3058 Building a Cupertino app with Flutter, add customer info issue
- [ ] https://github.com/flutter/website/issues/2864 List products for sale
- [ ] https://github.com/flutter/website/issues/2660 mistake in codelab 'Building a Cupertino app with Flutter'

This might seem like a lot, but there are even more filed against the starter codelabs, which is my next project.  :)

**Comment by domesticmouse** [comment]
I believe most of these issues have been fixed in the updated [Building a Cupertino app with Flutter](https://codelabs.developers.google.com/codelabs/flutter-cupertino/index.html#0) codelab. Thanks!
