### ISSUE TITLE
☂️ Improve Widget and Driver Tests sections

### ISSUE THREAD

**Issue by kentcb** [flutter/website#7795]
Per [this discussion](https://groups.google.com/forum/#!topic/flutter-dev/2yEf-VNAwPY), it seems widget tests are under-documented in these ways:

* unclear why UI appears small with black regions above and below it
* unclear whether that behavior can be overridden or modified in any way
* it was unclear to me that driver and widget tests were a different thing, and how they differ. That said, [this documentation](https://docs.flutter.dev/testing#widget-testing) seems pretty good. Perhaps I missed that when I was trying this stuff out.

Ultimately, what I want to do is use automate the execution of widget tests on my CI to take snapshots of the app at various points. This way, I can set up a feed for my test team to monitor to see if anything visual breaks during the development of an application. Of course, I will need to choose a resolution at which to take the snapshots, but I am unclear on how I can achieve this.

----

This should include:
- [ ] https://github.com/flutter/website/issues/2005
- [ ] https://github.com/flutter/website/issues/3609
- [ ] https://github.com/flutter/website/issues/4855
- [ ] https://github.com/flutter/website/issues/8022

**Comment by antfitch** [comment]
@kentcb because this issue is so old and there have been so many changes to Flutter, I'm not sure if this is still an issue. I'm going to tentatively close, but if you are absolutely certain this is still a problem, feel free to re-open this or create a new, fresh ticket. I'm also wondering if you might want to open a ticket with development? It sounds like this could be a dev issue that needs to be fixed if it hasn't already.
