### ISSUE TITLE
☂️ Updates for flavors page

### ISSUE THREAD

**Issue by MiraMarshall** [flutter/website#7979]
https://docs.flutter.dev/deployment/flavors/

TODOs for flavors page:

- [ ] Add/reference an app sample with free/paid flavors. 
- [ ] Update screenshots to display free and paid flavors. 
- [ ] Update page to better follow google developer documentation style and formatting guidelines
- [ ] Organize all iOS content under a single header
- [ ] Better clarify meaning of "desired flavors" in Android documentation
- [ ] Better format explanation of options in `build.gradle` 
- [ ] Full copy edit of page

----
Covers:
- [ ] https://github.com/flutter/website/issues/8743
- [ ] https://github.com/flutter/website/issues/8746
- [ ] https://github.com/flutter/website/issues/8238
- [ ] https://github.com/flutter/website/issues/9309

**Comment by MiraMarshall** [comment]
@jmagman

**Comment by jmagman** [comment]
@MiraMarshall is this a duplicate of https://github.com/flutter/website/issues/4321?

**Comment by jmagman** [comment]
Ah, no I see it's the follow-up TODOs from https://github.com/flutter/website/pull/7867.

**Comment by atsansone** [comment]
Move to #9976
