### ISSUE TITLE
☂ Add missing Cupertino widgets to the widget catalog

### ISSUE THREAD

**Issue by leighajarett** [flutter/website#8739]
I'm going to collect other missing Cupertino widgets from the Cupertino catalog here. This can be the umbrella bug:

The listed items were already in the list below.

### What information is missing?

In Flutter 3.10 we added two new Cupertino widgets. We should add those to the widget catalog.

The following **38** widgets appear in the API but not in the Widget Catalog.
- [ ] Add [CupertinoActionSheetAction](https://api.flutter.dev/flutter/cupertino/CupertinoActionSheetAction-class.html) to the Widget Catalog
- [ ] Add [CupertinoAdaptiveTextSelectionToolbar](https://api.flutter.dev/flutter/cupertino/CupertinoAdaptiveTextSelectionToolbar-class.html) to the Widget Catalog
- [ ] Add [CupertinoApp](https://api.flutter.dev/flutter/cupertino/CupertinoApp-class.html) to the Widget Catalog
- [ ] Add [CupertinoCheckbox](https://api.flutter.dev/flutter/cupertino/CupertinoCheckbox-class.html) to the Widget Catalog
- [ ] Add [CupertinoColors](https://api.flutter.dev/flutter/cupertino/CupertinoColors-class.html) to the Widget Catalog
- [ ] Add [CupertinoContextMenuAction](https://api.flutter.dev/flutter/cupertino/CupertinoContextMenuAction-class.html) to the Widget Catalog
- [ ] Add [CupertinoDesktopTextSelectionControls](https://api.flutter.dev/flutter/cupertino/CupertinoDesktopTextSelectionControls-class.html) to the Widget Catalog
- [ ] Add [CupertinoDesktopTextSelectionToolbar](https://api.flutter.dev/flutter/cupertino/CupertinoDesktopTextSelectionToolbar-class.html) to the Widget Catalog
- [ ] Add [CupertinoDesktopTextSelectionToolbarButton](https://api.flutter.dev/flutter/cupertino/CupertinoDesktopTextSelectionToolbarButton-class.html) to the Widget Catalog
- [ ] Add [CupertinoDialogRoute](https://api.flutter.dev/flutter/cupertino/CupertinoDialogRoute-class.html) to the Widget Catalog
- [ ] Add [CupertinoDynamicColor](https://api.flutter.dev/flutter/cupertino/CupertinoDynamicColor-class.html) to the Widget Catalog
- [ ] Add [CupertinoFormRow](https://api.flutter.dev/flutter/cupertino/CupertinoFormRow-class.html) to the Widget Catalog
- [ ] Add [CupertinoFormSection](https://api.flutter.dev/flutter/cupertino/CupertinoFormSection-class.html) to the Widget Catalog
- [ ] Add [CupertinoIcons](https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html) to the Widget Catalog
- [ ] Add [CupertinoIconThemeData](https://api.flutter.dev/flutter/cupertino/CupertinoIconThemeData-class.html) to the Widget Catalog
- [ ] Add [CupertinoListTileChevron](https://api.flutter.dev/flutter/cupertino/CupertinoListTileChevron-class.html) to the Widget Catalog
- [ ] Add [CupertinoLocalizations](https://api.flutter.dev/flutter/cupertino/CupertinoLocalizations-class.html) to the Widget Catalog
- [ ] Add [CupertinoMagnifier](https://api.flutter.dev/flutter/cupertino/CupertinoMagnifier-class.html) to the Widget Catalog
- [ ] Add [CupertinoModalPopupRoute](https://api.flutter.dev/flutter/cupertino/CupertinoModalPopupRoute-class.html) to the Widget Catalog
- [ ] Add [CupertinoNavigationBarBackButton](https://api.flutter.dev/flutter/cupertino/CupertinoNavigationBarBackButton-class.html) to the Widget Catalog
- [ ] Add [CupertinoPage](https://api.flutter.dev/flutter/cupertino/CupertinoPage-class.html) to the Widget Catalog
- [ ] Add [CupertinoPageRoute](https://api.flutter.dev/flutter/cupertino/CupertinoPageRoute-class.html) to the Widget Catalog
- [ ] Add [CupertinoPickerDefaultSelectionOverlay](https://api.flutter.dev/flutter/cupertino/CupertinoPickerDefaultSelectionOverlay-class.html) to the Widget Catalog
- [ ] Add [CupertinoRadio](https://api.flutter.dev/flutter/cupertino/CupertinoRadio-class.html) to the Widget Catalog
- [ ] Add [CupertinoScrollBehavior](https://api.flutter.dev/flutter/cupertino/CupertinoScrollBehavior-class.html) to the Widget Catalog
[ x] Add [CupertinoSliverRefreshControl](https://api.flutter.dev/flutter/cupertino/CupertinoSliverRefreshControl-class.html) to the Widget Catalog
- [ ] Add [CupertinoSpellCheckSuggestionsToolbar](https://api.flutter.dev/flutter/cupertino/CupertinoSpellCheckSuggestionsToolbar-class.html) to the Widget Catalog
- [ ] Add [CupertinoTabController](https://api.flutter.dev/flutter/cupertino/CupertinoTabController-class.html) to the Widget Catalog
- [ ] Add [CupertinoTextFormFieldRow](https://api.flutter.dev/flutter/cupertino/CupertinoTextFormFieldRow-class.html) to the Widget Catalog
- [ ] Add [CupertinoTextMagnifier](https://api.flutter.dev/flutter/cupertino/CupertinoTextMagnifier-class.html) to the Widget Catalog
- [ ] Add [CupertinoTextSelectionControls](https://api.flutter.dev/flutter/cupertino/CupertinoTextSelectionControls-class.html) to the Widget Catalog
- [ ] Add [CupertinoTextSelectionHandleControls](https://api.flutter.dev/flutter/cupertino/CupertinoTextSelectionHandleControls-class.html) to the Widget Catalog
- [ ] Add [CupertinoTextSelectionToolbar](https://api.flutter.dev/flutter/cupertino/CupertinoTextSelectionToolbar-class.html) to the Widget Catalog
- [ ] Add [CupertinoTextSelectionToolbarButton](https://api.flutter.dev/flutter/cupertino/CupertinoTextSelectionToolbarButton-class.html) to the Widget Catalog
- [ ] Add [CupertinoTextThemeData](https://api.flutter.dev/flutter/cupertino/CupertinoTextThemeData-class.html) to the Widget Catalog
- [ ] Add [CupertinoTheme](https://api.flutter.dev/flutter/cupertino/CupertinoTheme-class.html) to the Widget Catalog
- [ ] Add [CupertinoThemeData](https://api.flutter.dev/flutter/cupertino/CupertinoThemeData-class.html) to the Widget Catalog
- [ ] Add [CupertinoThumbPainter](https://api.flutter.dev/flutter/cupertino/CupertinoThumbPainter-class.html) to the Widget Catalog

**Comment by leighajarett** [comment]
It might be worth sanity checking this list with the [cupertino folder in the framework](https://github.com/flutter/flutter/tree/master/packages/flutter/lib/src/cupertino) to make sure there are not others that are missing.

I'm happy to answer any questions or review PRs.

**Comment by leighajarett** [comment]
Of these the ones I think we should prioritize adding are:

CupertinoCheckBox
CupertinoFormRow / Section 
CupertinoRadio
CupertinoSliverRefreshControl

@MitchellGoodwin are there others from the above list you think should be added to the catalog?

@atsansone I would defer to what the catalog does for Material widgets, they should have similar routes, text selection, and theme widgets
