### ISSUE TITLE
Incorporate high-quality cookbook recipes into sidenav when appropriate

### ISSUE THREAD

**Issue by parlough** [flutter/website#9013]
- [x] #9073
- [x] Incorporate maintenance cookbooks in the sidenav (https://github.com/flutter/website/pull/9125)
- [x] Incorporate navigation cookbooks in the sidenav (https://github.com/flutter/website/pull/9109)
- [x] Incorporate networking cookbooks in the sidenav (https://github.com/flutter/website/pull/9061, https://github.com/flutter/website/pull/9127)
- [x] Incorporate persistence cookbooks in the sidenav (https://github.com/flutter/website/pull/9128)
- [x] Incorporate testing cookbooks in the sidenav (https://github.com/flutter/website/pull/9125)

---

This should mostly until https://github.com/flutter/website/issues/9011 is completed:

- [x] #9140 (https://github.com/flutter/website/pull/9147)
- [x] #9141 (https://github.com/flutter/website/pull/9153)
- [x] #9142 (https://github.com/flutter/website/pull/9147, https://github.com/flutter/website/pull/9148)
- [x] #9143 (https://github.com/flutter/website/pull/9150)
- [x] #9144 (https://github.com/flutter/website/pull/9148)
- [x] Incorporate images cookbooks in the sidenav (https://github.com/flutter/website/pull/9130)
- [x] #9145
- [x] Incorporate plugins cookbooks in the sidenav (https://github.com/flutter/website/pull/9130)
