### ISSUE TITLE
☂️ Overhaul and introduce new theming/styling documentation

### ISSUE THREAD

**Issue by parlough** [flutter/website#9396]
This servers as an in-progress umbrella issue for updated and expanded theming documentation. Some potential areas to work on. Feel free to modify or add to this list. These entries may replace or augment existing documentation, and do not all necessarily belong in their own doc.

- [ ] An introduction to theming in Flutter, fallback order, common APIs, etc
- [ ] Apply and use the base app theme
- [ ] Create and switch between themes
- [ ] Override widget themes
- [ ] Configure styles based on widget state
- [ ] Create a custom Theme and ThemeData for your widget
