### ISSUE TITLE
☂️ Update Games Toolkit

### ISSUE THREAD

**Issue by atsansone** [flutter/website#9665]
Update or create the following documentation on docs.flutter.dev

### Architecture
- [x] #9743
- [x] Move Toolkits to top level of ToC
- [x] Create Games Toolkit and News Toolkit as subs in ToC
- [x] Move existing cookbooks to the Games Toolkit section

### Content
- [x] #9671
- [x] #9670
- [x] #9669
- [x] #9668

**Comment by parlough** [comment]
Related: https://github.com/flutter/website/issues/9398

As part of the IA followup, we were/are planning to add a new top-level category where the toolkits (and other similar topics) would live. 

However, I don't think it is best called "Toolkits". That provides no indication to the user what is actually contained within the category. In the linked issue I suggest "Use cases", but I was hoping to continue the discussion around the naming.

**Comment by atsansone** [comment]
Fixed in #9782
