### ISSUE TITLE
☂️ Refactor Flavors page

### ISSUE THREAD

**Issue by atsansone** [flutter/website#9976]
Update the Flavors page accounting for the following issues:

- [x] #8743
- [x] #8746
- [x] #8238
- [ ] #9309
- [x] #9359
- [ ] #9360
- [ ] #9361
- [ ] #9988 
- [ ] #9993
- [ ] #10309
- [ ] #10713 

This covers:

- [ ] Updating all screenshots for Xcode 15
- [ ] Updating iOS Xcode project configuration section
- [ ] Adding a sample app to the page
- [ ] Adding unique icons to each app flavor
- [ ] Adding docs for the appFlavor TL constant

https://docs.flutter.dev/deployment/flavors/

TODOs for flavors page:

- [ ] Add/reference an app sample with free/paid flavors. 
- [ ] Update screenshots to display free and paid flavors. 
- [ ] Update page to better follow google developer documentation style and formatting guidelines
- [ ] Organize all iOS content under a single header
- [ ] Better clarify meaning of "desired flavors" in Android documentation
- [ ] Better format explanation of options in `build.gradle` 
- [ ] Full copy edit of page

----
Covers:
- [x] https://github.com/flutter/website/issues/8743
- [x] https://github.com/flutter/website/issues/8746
- [x] https://github.com/flutter/website/issues/8238
- [ ] https://github.com/flutter/website/issues/9309
